<a href="https://colab.research.google.com/github/asmikhare/ML-Study-Jam/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

 It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

 - fixed type
 - faster to read less bytes of the memory
 - no type checking when iterating through objects
 - contiguous memory

 ```
 a= np.array([1,2,3])
 ```

### Remember to pip install numpy


In [ ]:
pip install numpy


In [ ]:
import numpy as np

In [ ]:
a= np.array([1,2,3,])
print(a)

[1 2 3]


In [ ]:
b= np.array([[7,3,8],[3,6,5]]) #2D array
print(b)

[[7 3 8]
 [3 6 5]]


In [ ]:
#Get Dimension
b. ndim

2

In [ ]:
b.ndim

In [ ]:
#Get shape
a.shape # has only 3 elements
b.shape #(2 rows colums)

(2, 3)

## Working with specific rows/ columns

In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r,c]
a[1,4]
a[1,-3]

12

In [ ]:
#Get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get specific column
a[:, 2]

array([ 3, 10])

In [ ]:
# [starting:ending:stepindex]
a[0,1:5]

array([2, 3, 4, 5])

In [ ]:
a[0,0:6:2]

array([1, 3, 5])

In [ ]:
#changing element value
a[1,5]=33

In [ ]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 33 14]]


### 3d Array

In [ ]:
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
b.ndim

3

In [ ]:
#Get specific element

b[0,0,2]

3

In [ ]:
b[0,:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#replacing

b[0,0,1]= 43
print(b)

[[[ 1 43  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Initializing different kind of arrays

In [ ]:
# ALL 0's array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
#All 1's
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# Any Other number
np.full((4,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
#Random decimal number array
np.random.rand(2,3)

array([[0.53313724, 0.27769951, 0.40444912],
       [0.77439502, 0.77958754, 0.88026074]])

In [ ]:
np.random.rand(2,3,4)

array([[[0.08312749, 0.18897783, 0.0025811 , 0.39143249],
        [0.84410614, 0.15462534, 0.65463733, 0.68510989],
        [0.96961188, 0.11670484, 0.09639638, 0.40505915]],

       [[0.7705251 , 0.00951264, 0.32500927, 0.91862956],
        [0.69785063, 0.86939305, 0.62280599, 0.63138795],
        [0.55098697, 0.92878476, 0.20455266, 0.1386375 ]]])

In [ ]:
# random integers
np.random.randint(1,10, size=(3,3))

array([[1, 5, 8],
       [7, 5, 5],
       [2, 8, 5]])

In [ ]:
# Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Mathematics

In [ ]:
a= np.array([1,2,3])

In [ ]:
a*2

array([2, 4, 6])

In [ ]:
a/2

array([0.5, 1. , 1.5])

In [ ]:
a//2

array([0, 1, 1])

In [ ]:
a%2

array([1, 0, 1])

In [ ]:
a +2

array([3, 4, 5])

In [ ]:
a-1

array([0, 1, 2])

In [ ]:
b=np.array([2,3,4])

In [ ]:
b+a

array([3, 5, 7])

In [ ]:
a**b

array([ 1,  8, 81])

In [ ]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

#Linear Algebra

In [ ]:
a= np.full((2,3), 3)
print(a)

b=np.ones((3,2))
print(b)

[[3 3 3]
 [3 3 3]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
np.matmul(a,b) #matrix Multiplication

array([[9., 9.],
       [9., 9.]])

In [ ]:
#Finding the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
np.linalg.eig(c) #eigen value

EigResult(eigenvalues=array([1., 1., 1.]), eigenvectors=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))

[View more algebra functions](https://numpy.org/learn/)

In [ ]:
stats= np.array([[1,3,4],[2,5,6]])
np.min(stats)

1

In [ ]:
np.max(stats)

6

In [ ]:
np.sum(stats)

21